paths:
    /api/carts:
        get:
            summary: Retrieve a list of carts
            parameters:
                - in: query
                  name: limit
                  schema:
                      type: integer
                  description: Limit number of carts to return
                - in: query
                  name: page
                  schema:
                      type: integer
                  description: Page number for carts pagination
                - in: query
                  name: sort
                  schema:
                      type: string
                  description: Sorting order ('asc' or 'desc')
                - in: query
                  name: query
                  schema:
                      type: string
                  description: Query for filtering carts by category
            responses:
                '200':
                    description: A list of carts
        post:
            summary: Create a new cart
            responses:
                '200':
                    description: The created cart

    /api/carts/{cid}:
        get:
            summary: Retrieve a specific cart
            parameters:
                - in: path
                  name: cid
                  schema:
                      type: string
                  required: true
                  description: Cart ID
            responses:
                '200':
                    description: The requested cart
                '404':
                    description: Cart not found
        put:
            summary: Update a specific cart
            parameters:
                - in: path
                  name: cid
                  schema:
                      type: string
                  required: true
                  description: Cart ID
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                products:
                                    type: array
                                    items:
                                        type: object
                                        properties:
                                            productId:
                                                type: string
                                            quantity:
                                                type: integer
            responses:
                '200':
                    description: The updated cart
                '500':
                    description: Error message
        delete:
            summary: Remove all products from a specific cart
            parameters:
                - in: path
                  name: cid
                  schema:
                      type: string
                  required: true
                  description: Cart ID
            responses:
                '200':
                    description: The updated cart
                '500':
                    description: Error message

    /api/carts/{cid}/products/{pid}:
        put:
            summary: Add a product to a specific cart or update its quantity
            parameters:
                - in: path
                  name: cid
                  schema:
                      type: string
                  required: true
                  description: Cart ID
                - in: path
                  name: pid
                  schema:
                      type: string
                  required: true
                  description: Product ID
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                quantity:
                                    type: integer
            responses:
                '200':
                    description: The updated product
                '500':
                    description: Error message
        delete:
            summary: Remove a product from a specific cart
            parameters:
                - in: path
                  name: cid
                  schema:
                      type: string
                  required: true
                  description: Cart ID
                - in: path
                  name: pid
                  schema:
                      type: string
                  required: true
                  description: Product ID
            responses:
                '200':
                    description: Message indicating the product was removed
                '500':
                    description: Error message

    /api/carts/{cid}/purchase:
        post:
            summary: Purchase all products in a specific cart
            parameters:
                - in: path
                  name: cid
                  schema:
                      type: string
                  required: true
                  description: Cart ID
            responses:
                '200':
                    description: Message indicating the purchase was successful
                '500':
                    description: Error message
